[env:ESP32_C6_env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino

build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ESP32_C6_env

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.11
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
	https://github.com/olikraus/U8g2_for_Adafruit_GFX

monitor_speed = 115200
